// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb1QA0WCRUlmt6yISyTQhWs4VHbjVAeus',
    appId: '1:552756935986:web:98d669e2abc4c0918f2b2b',
    messagingSenderId: '552756935986',
    projectId: 'dipetakan-57d6b',
    authDomain: 'dipetakan-57d6b.firebaseapp.com',
    storageBucket: 'dipetakan-57d6b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD61IYwMTfdyXWK3Kd3z66NHI5RAz-ZF-8',
    appId: '1:552756935986:android:864eb3b626d41d1f8f2b2b',
    messagingSenderId: '552756935986',
    projectId: 'dipetakan-57d6b',
    storageBucket: 'dipetakan-57d6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3Z8B1_3bHOxmhv53TVM_SRNb8cQ7uhc8',
    appId: '1:552756935986:ios:c0ea32ff884b7bba8f2b2b',
    messagingSenderId: '552756935986',
    projectId: 'dipetakan-57d6b',
    storageBucket: 'dipetakan-57d6b.appspot.com',
    androidClientId: '552756935986-jd3njcecbuv6326rq662i30t2r39i697.apps.googleusercontent.com',
    iosClientId: '552756935986-nl9am7g47l94aseqp1uglbdpkdjflggn.apps.googleusercontent.com',
    iosBundleId: 'com.example.dipetakan',
  );

}