name: dipetakan
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.0
  intl: ^0.19.0
  lottie: ^3.1.0
  connectivity_plus: ^5.0.1
  flutter_native_splash: ^2.4.0
  timeline_tile: ^2.0.0
  flutter_image_compress: ^2.3.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  path_provider: ^2.1.4

  # Icons & UI
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  shimmer: ^3.0.0

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Google Maps
  google_maps_flutter: ^2.5.3

  # Feature
  image_picker: ^1.0.7
  location: ^5.0.0

  #Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  # Local Assets
  assets :
  - assets/fonts/
  - assets/icons/
  - assets/images/
  - assets/logos/
  - assets/sampledata/
  - assets/images/animations/

  # Local Fonts
  fonts :
  - family : Inter
    fonts :
    - asset : assets\fonts\Inter-Regular.ttf
      weight : 400
    - asset : assets\fonts\Inter-Medium.ttf
      weight : 500
    - asset : assets\fonts\Inter-SemiBold.ttf
      weight : 600
    - asset : assets\fonts\Inter-Bold.ttf
      weight : 700
    - asset : assets\fonts\Inter-ExtraBold.ttf
      weight : 800


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
