// // import 'dart:convert';

// class UserModel {
//   final int id;
//   String fullName;
//   String username;
//   String email;
//   String phoneNo;
//   String profilePicture;

//   UserModel({
//     required this.id,
//     required this.fullName,
//     required this.username,
//     required this.email,
//     required this.phoneNo,
//     required this.profilePicture,
//   });

//   static UserModel empty() => UserModel(
//       id: 0,
//       fullName: '',
//       username: '',
//       email: '',
//       phoneNo: '',
//       profilePicture: '');

//   ///Convert model to JSON structure for storing data in PostgreSQL
//   Map<String, dynamic> toJson() {
//     return {
//       'id': id, // Assuming 'id' is auto-generated by the database
//       'NamaLengkap': fullName,
//       'Username': username,
//       'Email': email,
//       'NoTelepon': phoneNo,
//       'FotoProfil': profilePicture,
//     };
//   }

//   ///Factory method to create UserModel from JSON
//   factory UserModel.fromJson(Map<String, dynamic> json) {
//     return UserModel(
//       id: json['id'] ?? 0,
//       fullName: json['NamaLengkap'] ?? '',
//       username: json['Username'] ?? '',
//       email: json['Email'] ?? '',
//       phoneNo: json['NoTelepon'] ?? '',
//       profilePicture: json['FotoProfil'] ?? '',
//     );
//   }
// }
